id: A24E62DB1
base_file: f2329.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:10:22.407382
  last_modified_at: 2022-05-30 23:10:22.407390
